INSERT INTO party (name, abbreviation, color)
VALUES ('Sozialdemokratische Partei Deutschlands', 'SPD', 'E3000F'),
       ('Christlich Demokratische Union Deutschlands', 'CDU', '151518'),
       ('Bündnis 90/Die Grünen', 'Grüne', '46962B'),
       ('Freie Demokratische Partei', 'FDP', 'FFFF00'),
       ('Die Linke', 'Linke', 'BE3075'),
       ('Christlich-Soziale Union in Bayern e.V.', 'CSU', '151518'),
       ('FREIE WÄHLER', '', 'FF8000'),
       ('PARTEI MENSCH UMWELT TIERSCHUTZ', 'Tierschutzpartei', '006D77'),
       ('Basisdemokratische Partei Deutschland', '', '4D4C4D'),
       ('Partei für Arbeit, Rechtsstaat, Tierschutz, Elitenförderung und basisdemokratische Initiative', '', ''),
       ('Team Todenhöfer – Die Gerechtigkeitspartei', '', ''),
       ('Piratenpartei Deutschland', '', ''),
       ('Volt Deutschland', '', ''),
       ('Ökologisch-Demokratische Partei', '', ''),
       ('Nationaldemokratische Partei Deutschlands', '', ''),
       ('Südschleswigscher Wählerverband', '', ''),
       ('Partei für Gesundheitsforschung', '', ''),
       ('Partei der Humanisten', '', ''),
       ('Bündnis C - Christen für Deutschland', '', ''),
       ('Bayernpartei', '', ''),
       ('V-Partei³ - Partei für Veränderung, Vegetarier und Veganer', '', ''),
       ('UNABHÄNGIGE für bürgernahe Demokratie', '', ''),
       ('Die Grauen – Für alle Generationen', '', ''),
       ('Die Urbane. Eine HipHop Partei', '', ''),
       ('Marxistisch-Leninistische Partei Deutschlands', '', ''),
       ('Deutsche Kommunistische Partei', '', ''),
       ('Allianz für Menschenrechte, Tier- und Naturschutz', '', ''),
       ('Europäische Partei LIEBE', '', ''),
       ('Liberal-Konservative Reformer', '', ''),
       ('Partei für Kinder, Jugendliche und Familien  – Lobbyisten für Kinder –', '', ''),
       ('DER DRITTE WEG', '', ''),
       ('Gartenpartei', '', ''),
       ('Bürgerbewegung für Fortschritt und Wandel', '', ''),
       ('DEMOKRATIE IN BEWEGUNG', '', ''),
       ('Menschliche Welt - für das Wohl und Glücklichsein aller', '', ''),
       ('diePinken/BÜNDNIS21', '', ''),
       ('Partei des Fortschritts', '', ''),
       ('Sozialistische Gleichheitspartei, Vierte Internationale', '', ''),
       ('Bürgerrechtsbewegung Solidarität', '', ''),
       ('Ab jetzt...Demokratie durch Volksabstimmung - Politik für die Menschen', '', ''),
       ('bergpartei, die überpartei - ökoanarchistisch-realdadaistisches sammelbecken', '', ''),
       ('DIE SONSTIGEN - X', '', ''),
       ('Familien-Partei Deutschlands', '', ''),
       ('Graue Panther', '', ''),
       ('Klimaliste Baden-Württemberg', '', ''),
       ('Thüringer Heimatpartei', '', ''),
       ('Übrige', 'Übrige', 'C0C0C0'),
       ('Alternative für Deutschland', 'AfD', '009EE0');


INSERT INTO state (name)
VALUES ('Schleswig-Holstein'),
       ('Hamburg'),
       ('Niedersachsen'),
       ('Bremen'),
       ('Nordrhein-Westfalen'),
       ('Hessen'),
       ('Rheinland-Pfalz'),
       ('Baden-Württemberg'),
       ('Bayern'),
       ('Saarland'),
       ('Berlin'),
       ('Brandenburg'),
       ('Mecklenburg-Vorpommern'),
       ('Sachsen'),
       ('Sachsen-Anhalt'),
       ('Thüringen');