-- Seed data for the statistics domains (docs/08-additional-data-schema.md).
-- stat_party ids are stable; aliases cover every label variant observed in the
-- source files (brief_wkr/kreis 2009-2025, RWS 2017-2025, Zeitreihen ab 1953/57).
-- The importer hard-fails on labels that do not resolve via stat_party_alias.

INSERT INTO dataset (id, name, source_url, license, note)
VALUES ('rws', 'Repräsentative Wahlstatistik',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/repraesentative-wahlstatistik.html',
        'dl-de/by-2-0',
        'Stichprobenstatistik (ca. 2 300 Wahlbezirke), hochgerechnete Werte. Erhoben werden Geburtsjahresgruppen, keine exakten Altersgruppen; die Gruppengrenzen ändern sich je Wahl. Ab 2021 enthalten die Ergebnisse der Männer auch Personen mit Geschlechtsmerkmal divers oder ohne Eintrag.'),
       ('rws_series', 'Repräsentative Wahlstatistik — Zeitreihen seit 1953',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/repraesentative-wahlstatistik.html',
        'dl-de/by-2-0',
        'Bundesergebnisse nach Geschlecht und Altersgruppen seit 1953. Altersgruppen-Grenzen wechseln zwischen den Ären; 1994 und 1998 war die Statistik ausgesetzt.'),
       ('absentee_series', 'Wahlschein- und Briefwahlbeteiligung seit 1957',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/weitere-ergebnisse.html',
        'dl-de/by-2-0',
        'Wahlberechtigte mit Wahlschein und Wählende nach Stimmabgabeart, je Land und Bund seit 1957.'),
       ('ballot_wkr', 'Urnen- und Briefwahlergebnisse nach Wahlkreisen',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/weitere-ergebnisse.html',
        'dl-de/by-2-0',
        'Endgültige Erst- und Zweitstimmen getrennt nach Urnen- und Briefwahlbezirken, je Wahlkreis (2009-2025). Wahlberechtigte werden nur der Urnenwahl zugerechnet.'),
       ('kreis', 'Ergebnisse nach kreisfreien Städten und Landkreisen',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/ergebnisse/weitere-ergebnisse.html',
        'dl-de/by-2-0',
        'Endgültige Ergebnisse je Kreis (amtliche Kennziffer/AGS), 2009-2025. Kreisreformen (z. B. Mecklenburg-Vorpommern 2011) schränken die Vergleichbarkeit über Jahre ein; bewusst keine kanonische Kreis-Entität.'),
       ('strukturdaten', 'Strukturdaten der Wahlkreise',
        'https://www.bundeswahlleiterin.de/bundestagswahlen/2025/strukturdaten.html',
        'dl-de/by-2-0',
        'Sozioökonomische Kennzahlen je Wahlkreis, Land und Bund (2013-2025). Arbeitsmarkt-Indikatoren: © Statistik der Bundesagentur für Arbeit. Stichtage der Kennzahlen unterscheiden sich je Wahl (siehe indicator_source_column.reference_date).');

INSERT INTO dataset_note (dataset_id, election_year, note)
VALUES ('rws', 2021, 'Stand der Hauptwahl vom 26.09.2021 — die Wiederholungswahl in Teilen Berlins (Februar 2024) ist NICHT enthalten.'),
       ('ballot_wkr', 2021, 'Einschließlich der Wiederholungswahl in Teilen Berlins vom 11.02.2024.'),
       ('kreis', 2021, 'Einschließlich der Wiederholungswahl in Teilen Berlins vom 11.02.2024.'),
       ('rws_series', NULL, '1953: Bundesergebnis ohne Rheinland-Pfalz und Bayern. 1953/1957: reine Stichprobenwerte (nicht hochgerechnet); CSU in CDU enthalten. Bis 1990 nicht kalibriert, 1957-1990 Wählende nur ohne Wahlschein. 1994/1998 ausgesetzt.'),
       ('rws', NULL, 'Die "dar."-Spalten (is_memo = 1) sind nachrichtliche Teilmengen von Sonstige und dürfen nicht mitsummiert werden. Summen sind hochgerechnet und gerundet — Zeilensummen weichen minimal ab.');

INSERT INTO gender (code, note)
VALUES ('total', 'Summe'),
       ('m', 'ab 2021 einschließlich divers und ohne Geschlechtseintrag (Quelle: m|d|o)'),
       ('w', NULL);

-- age brackets appearing in btw_rws_wb-1953 / btw_rws_zwst-1953
INSERT INTO age_group (id, label, age_from, age_to)
VALUES (0, 'total', NULL, NULL),
       (1, '18-20', 18, 20),
       (2, '18-24', 18, 24),
       (3, '21-24', 21, 24),
       (4, '21-29', 21, 29),
       (5, '25-29', 25, 29),
       (6, '25-34', 25, 34),
       (7, '30-34', 30, 34),
       (8, '30-39', 30, 39),
       (9, '30-44', 30, 44),
       (10, '30-59', 30, 59),
       (11, '35-39', 35, 39),
       (12, '35-44', 35, 44),
       (13, '40-44', 40, 44),
       (14, '40-49', 40, 49),
       (15, '45-49', 45, 49),
       (16, '45-59', 45, 59),
       (17, '50-59', 50, 59),
       (18, '60-69', 60, 69),
       (19, '>=60', 60, NULL),
       (20, '>=70', 70, NULL);

-- pseudo entries (1-9), canonically mapped parties (10-56), micro parties
-- without canonical row (60+, party_id NULL — additive when the canon grows)
INSERT INTO stat_party (id, code, party_id, note)
VALUES (1, 'TOTAL', NULL, 'Summenzeile/-spalte der Quelle (hochgerechnet, nicht aus den Parteiwerten ableitbar)'),
       (2, 'INVALID', NULL, 'Ungültige Stimmen'),
       (3, 'SONSTIGE', NULL, 'Restkategorie der RWS-/Zeitreihen-Dateien (Parteienkorb variiert je Wahl)'),
       (4, 'UEBRIGE', 49, 'Restkategorie der Wahlkreis-/Kreisdateien (entspricht kerg "Übrige")'),
       (5, 'CDU_CSU', NULL, 'Union kombiniert (nur ab57-Zeitreihe)'),
       (6, 'WGR_EB', NULL, 'Wählergruppen/Einzelbewerber (nur Erststimmen); 2021 als "sonstige" bezeichnet'),
       (10, 'SPD', 1, NULL),
       (11, 'CDU', 2, 'Zeitreihe 1953/1957: CSU-Ergebnisse in CDU enthalten (siehe dataset_note)'),
       (12, 'GRUENE', 3, NULL),
       (13, 'FDP', 4, NULL),
       (14, 'LINKE', 5, 'Zeitreihen-Label "PDS/Die Linke" eingeschlossen'),
       (15, 'CSU', 6, NULL),
       (16, 'FW', 7, NULL),
       (17, 'TIERSCHUTZPARTEI', 8, NULL),
       (18, 'BASIS', 9, NULL),
       (19, 'DIE_PARTEI', 10, NULL),
       (20, 'TEAM_TODENHOEFER', 11, NULL),
       (21, 'PIRATEN', 12, NULL),
       (22, 'VOLT', 13, NULL),
       (23, 'OEDP', 14, NULL),
       (24, 'NPD', 15, NULL),
       (25, 'SSW', 16, NULL),
       (26, 'GESUNDHEITSFORSCHUNG', 17, '2025 als "Verjüngungsforschung"'),
       (27, 'PDH', 18, NULL),
       (28, 'BUENDNIS_C', 19, NULL),
       (29, 'BP', 20, NULL),
       (30, 'V_PARTEI', 21, NULL),
       (31, 'UNABHAENGIGE', 22, NULL),
       (32, 'DIE_GRAUEN', 23, NULL),
       (33, 'DIE_URBANE', 24, NULL),
       (34, 'MLPD', 25, NULL),
       (35, 'DKP', 26, NULL),
       (36, 'TIERSCHUTZALLIANZ', 27, NULL),
       (37, 'LIEBE', 28, NULL),
       (38, 'LKR', 29, NULL),
       (39, 'DRITTER_WEG', 31, NULL),
       (40, 'GARTENPARTEI', 32, '2017 als "MG" (Magdeburger Gartenpartei)'),
       (41, 'BUERGERBEWEGUNG', 33, NULL),
       (42, 'DIB', 34, NULL),
       (43, 'MENSCHLICHE_WELT', 35, NULL),
       (44, 'BUENDNIS21', 36, NULL),
       (45, 'PDF', 37, NULL),
       (46, 'SGP', 38, NULL),
       (47, 'BUESO', 39, NULL),
       (48, 'VOLKSABSTIMMUNG', 40, NULL),
       (49, 'BERGPARTEI', 41, NULL),
       (50, 'FAMILIE', 43, NULL),
       (51, 'GRAUE_PANTHER', 44, NULL),
       (52, 'KLIMALISTE_BW', 45, NULL),
       (53, 'THP', 46, NULL),
       (54, 'REP', 47, NULL),
       (55, 'BSW', 48, NULL),
       (56, 'AFD', 50, NULL),
       (60, 'ADM', NULL, 'Allianz der Mitte (2009)'),
       (61, 'BGD', NULL, 'Bund für Gesamtdeutschland (2013)'),
       (62, 'BIG', NULL, 'Bündnis für Innovation und Gerechtigkeit (2013)'),
       (63, 'BUENDNIS_21_RRP', NULL, 'Bündnis 21/RRP (2013)'),
       (64, 'RRP', NULL, 'Rentnerinnen- und Rentner-Partei (2009)'),
       (65, 'DIE_VIOLETTEN', NULL, NULL),
       (66, 'DIE_FRAUEN', NULL, NULL),
       (67, 'DIE_EINHEIT', NULL, NULL),
       (68, 'DIE_RECHTE', NULL, NULL),
       (69, 'FREIE_UNION', NULL, NULL),
       (70, 'MIETERPARTEI', NULL, NULL),
       (71, 'NEUE_LIBERALE', NULL, NULL),
       (72, 'NEIN', NULL, 'NEIN!-Idee (2013)'),
       (73, 'PDV', NULL, 'Partei der Vernunft'),
       (74, 'PBC', NULL, 'Partei Bibeltreuer Christen'),
       (75, 'PRO_DEUTSCHLAND', NULL, NULL),
       (76, 'RENTNER', NULL, NULL),
       (77, 'ZENTRUM', NULL, NULL),
       (78, 'BUENDNIS_DEUTSCHLAND', NULL, '2025, ohne kanonische Partei (kerg-Spalte ebenfalls unmapped)'),
       (79, 'MERA25', NULL, '2025, ohne kanonische Partei'),
       (80, 'WERTEUNION', NULL, '2025, ohne kanonische Partei'),
       (81, 'AD_DEMOKRATEN', NULL, 'Allianz Deutscher Demokraten (2017)'),
       (82, 'BGE', NULL, 'Bündnis Grundeinkommen (2017)'),
       (83, 'CM', NULL, 'Christliche Mitte (2009)'),
       (84, 'DM', NULL, 'Deutsche Mitte (2017)'),
       (85, 'DVU', NULL, 'Deutsche Volksunion (2009)'),
       (86, 'FWD', NULL, 'Freie Wähler Deutschland (2009)'),
       (87, 'LFK', 30, 'Lobbyisten für Kinder (2021)'),
       (88, 'NICHTWAEHLER', NULL, 'Pseudo-Spalte der 2013-Dateien (auch in kerg 2013 vorhanden, dort unmapped)'),
       (89, 'PARTEI_DER_NICHTWAEHLER', NULL, '2017');

INSERT INTO stat_party_alias (alias, stat_party_id)
VALUES ('Summe', 1),
       ('Ungültig', 2),
       ('ungültig', 2),
       ('Sonstige', 3),
       ('Übrige', 4),
       ('CDU, CSU', 5),
       ('WGr/EB', 6),
       ('sonstige', 6),
       ('SPD', 10),
       ('CDU', 11),
       ('GRÜNE', 12),
       ('FDP', 13),
       ('DIE LINKE', 14),
       ('Die Linke', 14),
       ('PDS/Die Linke', 14),
       ('CSU', 15),
       ('FREIE WÄHLER', 16),
       ('Tierschutzpartei', 17),
       ('Die Tierschutzpartei', 17),
       ('dieBasis', 18),
       ('Die PARTEI', 19),
       ('Team Todenhöfer', 20),
       ('PIRATEN', 21),
       ('Volt', 22),
       ('ÖDP', 23),
       ('ödp', 23),
       ('NPD', 24),
       ('SSW', 25),
       ('Gesundheitsforschung', 26),
       ('Verjüngungsforschung', 26),
       ('Die Humanisten', 27),
       ('PdH', 27),
       ('Bündnis C', 28),
       ('BP', 29),
       ('V-Partei³', 30),
       ('UNABHÄNGIGE', 31),
       ('Die Grauen', 32),
       ('du', 33),
       ('du.', 33),
       ('MLPD', 34),
       ('DKP', 35),
       ('Tierschutzallianz', 36),
       ('LIEBE', 37),
       ('LKR', 38),
       ('III. Weg', 39),
       ('Gartenpartei', 40),
       ('MG', 40),
       ('BÜRGERBEWEGUNG', 41),
       ('DiB', 42),
       ('MENSCHLICHE WELT', 43),
       ('Bündnis21', 44),
       ('PdF', 45),
       ('SGP', 46),
       ('BüSo', 47),
       ('Volksabstimmung', 48),
       ('Volksab stimmung', 48),
       ('B', 49),
       ('B*', 49),
       ('Bergpartei', 49),
       ('FAMILIE', 50),
       ('Graue Panther', 51),
       ('KlimalisteBW', 52),
       ('THP', 53),
       ('REP', 54),
       ('BSW', 55),
       ('AfD', 56),
       ('ADM', 60),
       ('BGD', 61),
       ('BIG', 62),
       ('Bündnis 21/RRP', 63),
       ('RRP', 64),
       ('DIE VIOLETTEN', 65),
       ('DIE FRAUEN', 66),
       ('DIE EINHEIT', 67),
       ('DIE RECHTE', 68),
       ('Freie Union', 69),
       ('MIETERPARTEI', 70),
       ('Neue Liberale', 71),
       ('NEIN', 72),
       ('NEIN!', 72),
       ('PARTEI DER VERNUNFT', 73),
       ('PDV', 73),
       ('PBC', 74),
       ('pro Deutschland', 75),
       ('RENTNER', 76),
       ('ZENTRUM', 77),
       ('BÜNDNIS DEUTSCHLAND', 78),
       ('MERA25', 79),
       ('WerteUnion', 80),
       ('AD-DEMOKRATEN', 81),
       ('BGE', 82),
       ('CM', 83),
       ('DM', 84),
       ('DVU', 85),
       ('FWD', 86),
       ('LfK', 87),
       ('PSG', 46),
       ('Nichtwähler', 88),
       ('Nicht- wähler', 88),
       ('Partei der Nichtwähler', 89);
