INSERT INTO party (name, abbreviation, color)
VALUES ('Sozialdemokratische Partei Deutschlands', 'SPD', 'E3000F'),
       ('Christlich Demokratische Union Deutschlands', 'CDU', '576164'),
       ('Bündnis 90/Die Grünen', 'Grüne', '46962B'),
       ('Freie Demokratische Partei', 'FDP', 'F7BC3D'),
       ('Die Linke', 'Linke', 'BE3075'),
       ('Christlich-Soziale Union in Bayern e.V.', 'CSU', '004B76'),
       ('FREIE WÄHLER', 'FW', 'FF8000'),
       ('PARTEI MENSCH UMWELT TIERSCHUTZ', 'Tierschutzpartei', '006D77'),
       ('Basisdemokratische Partei Deutschland', '', '4D4C4D'),
       ('Partei für Arbeit, Rechtsstaat, Tierschutz, Elitenförderung und basisdemokratische Initiative', 'Die PARTEI', ''),
       ('Team Todenhöfer – Die Gerechtigkeitspartei', '', ''),
       ('Piratenpartei Deutschland', 'PIRATEN', ''),
       ('Volt Deutschland', 'Volt', ''),
       ('Ökologisch-Demokratische Partei', 'ÖDP', ''),
       ('Nationaldemokratische Partei Deutschlands', 'NPD', ''),
       ('Südschleswigscher Wählerverband', 'SSW', ''),
       ('Partei für Gesundheitsforschung', '', ''),
       ('Partei der Humanisten', '', ''),
       ('Bündnis C - Christen für Deutschland', '', ''),
       ('Bayernpartei', 'BP', ''),
       ('V-Partei³ - Partei für Veränderung, Vegetarier und Veganer', '', ''),
       ('UNABHÄNGIGE für bürgernahe Demokratie', '', ''),
       ('Die Grauen – Für alle Generationen', '', ''),
       ('Die Urbane. Eine HipHop Partei', '', ''),
       ('Marxistisch-Leninistische Partei Deutschlands', 'MLPD', ''),
       ('Deutsche Kommunistische Partei', 'DKP', ''),
       ('Allianz für Menschenrechte, Tier- und Naturschutz', '', ''),
       ('Europäische Partei LIEBE', '', ''),
       ('Liberal-Konservative Reformer', '', ''),
       ('Partei für Kinder, Jugendliche und Familien  – Lobbyisten für Kinder –', '', ''),
       ('DER DRITTE WEG', '', ''),
       ('Gartenpartei', '', ''),
       ('Bürgerbewegung für Fortschritt und Wandel', '', ''),
       ('DEMOKRATIE IN BEWEGUNG', '', ''),
       ('Menschliche Welt - für das Wohl und Glücklichsein aller', '', ''),
       ('diePinken/BÜNDNIS21', '', ''),
       ('Partei des Fortschritts', '', ''),
       ('Sozialistische Gleichheitspartei, Vierte Internationale', 'PSG', ''),
       ('Bürgerrechtsbewegung Solidarität', 'BüSo', ''),
       ('Ab jetzt...Demokratie durch Volksabstimmung - Politik für die Menschen', 'Volksabstimmung', ''),
       ('bergpartei, die überpartei - ökoanarchistisch-realdadaistisches sammelbecken', '', ''),
       ('DIE SONSTIGEN - X', '', ''),
       ('Familien-Partei Deutschlands', 'FAMILIE', ''),
       ('Graue Panther', '', ''),
       ('Klimaliste Baden-Württemberg', '', ''),
       ('Thüringer Heimatpartei', '', ''),
       ('DIE REPUBLIKANER', 'REP', '0075BE'),
       ('Bündnis Sahra Wagenknecht - Vernunft und Gerechtigkeit', 'BSW', '7D254F'),
       ('Übrige', 'Übrige', 'C0C0C0'),
       ('Alternative für Deutschland', 'AfD', '009EE0');

INSERT INTO state (name, abbreviation)
VALUES ('Schleswig-Holstein', 'SH'),
       ('Hamburg', 'HH'),
       ('Niedersachsen', 'NI'),
       ('Bremen', 'HB'),
       ('Nordrhein-Westfalen', 'NW'),
       ('Hessen', 'HE'),
       ('Rheinland-Pfalz', 'RP'),
       ('Baden-Württemberg', 'BW'),
       ('Bayern', 'BY'),
       ('Saarland', 'SL'),
       ('Berlin', 'BE'),
       ('Brandenburg', 'BB'),
       ('Mecklenburg-Vorpommern', 'MV'),
       ('Sachsen', 'SN'),
       ('Sachsen-Anhalt', 'ST'),
       ('Thüringen', 'TH');

INSERT INTO constituency (state_id, name)
VALUES (901, 'Flensburg – Schleswig'),
       (901, 'Nordfriesland – Dithmarschen Nord'),
       (901, 'Steinburg – Dithmarschen Süd'),
       (901, 'Rendsburg-Eckernförde'),
       (901, 'Kiel'),
       (901, 'Plön – Neumünster'),
       (901, 'Pinneberg'),
       (901, 'Segeberg – Stormarn-Mitte'),
       (901, 'Ostholstein – Stormarn-Nord'),
       (901, 'Herzogtum Lauenburg – Stormarn-Süd'),
       (901, 'Lübeck'),
       (902, 'Hamburg-Mitte'),
       (902, 'Hamburg-Altona'),
       (902, 'Hamburg-Eimsbüttel'),
       (902, 'Hamburg-Nord'),
       (902, 'Hamburg-Wandsbek'),
       (902, 'Hamburg-Bergedorf – Harburg'),
       (903, 'Aurich – Emden'),
       (903, 'Unterems'),
       (903, 'Friesland – Wilhelmshaven – Wittmund'),
       (903, 'Oldenburg – Ammerland'),
       (903, 'Delmenhorst – Wesermarsch – Oldenburg-Land'),
       (903, 'Cuxhaven – Stade II'),
       (903, 'Stade I – Rotenburg II'),
       (903, 'Mittelems'),
       (903, 'Cloppenburg – Vechta'),
       (903, 'Diepholz – Nienburg I'),
       (903, 'Osterholz – Verden'),
       (903, 'Rotenburg I – Heidekreis'),
       (903, 'Harburg'),
       (903, 'Lüchow-Dannenberg – Lüneburg'),
       (903, 'Osnabrück-Land'),
       (903, 'Stadt Osnabrück'),
       (903, 'Nienburg II – Schaumburg'),
       (903, 'Stadt Hannover I'),
       (903, 'Stadt Hannover II'),
       (903, 'Hannover-Land I'),
       (903, 'Celle – Uelzen'),
       (903, 'Gifhorn – Peine'),
       (903, 'Hameln-Pyrmont – Holzminden'),
       (903, 'Hannover-Land II'),
       (903, 'Hildesheim'),
       (903, 'Salzgitter – Wolfenbüttel'),
       (903, 'Braunschweig'),
       (903, 'Helmstedt – Wolfsburg'),
       (903, 'Goslar – Northeim – Osterode'),
       (903, 'Göttingen'),
       (904, 'Bremen I'),
       (904, 'Bremen II – Bremerhaven'),
       (905, 'Aachen I'),
       (905, 'Aachen II'),
       (905, 'Heinsberg'),
       (905, 'Düren'),
       (905, 'Rhein-Erft-Kreis I'),
       (905, 'Euskirchen – Rhein-Erft-Kreis II'),
       (905, 'Köln I'),
       (905, 'Köln II'),
       (905, 'Köln III'),
       (905, 'Bonn'),
       (905, 'Rhein-Sieg-Kreis I'),
       (905, 'Rhein-Sieg-Kreis II'),
       (905, 'Oberbergischer Kreis'),
       (905, 'Rheinisch-Bergischer Kreis'),
       (905, 'Leverkusen – Köln IV'),
       (905, 'Wuppertal I'),
       (905, 'Solingen – Remscheid – Wuppertal II'),
       (905, 'Mettmann I'),
       (905, 'Mettmann II'),
       (905, 'Düsseldorf I'),
       (905, 'Düsseldorf II'),
       (905, 'Neuss I'),
       (905, 'Mönchengladbach'),
       (905, 'Krefeld I – Neuss II'),
       (905, 'Viersen'),
       (905, 'Kleve'),
       (905, 'Wesel I'),
       (905, 'Krefeld II – Wesel II'),
       (905, 'Duisburg I'),
       (905, 'Duisburg II'),
       (905, 'Oberhausen – Wesel III'),
       (905, 'Mülheim – Essen I'),
       (905, 'Essen II'),
       (905, 'Essen III'),
       (905, 'Recklinghausen I'),
       (905, 'Recklinghausen II'),
       (905, 'Gelsenkirchen'),
       (905, 'Steinfurt I – Borken I'),
       (905, 'Bottrop – Recklinghausen III'),
       (905, 'Borken II'),
       (905, 'Coesfeld – Steinfurt II'),
       (905, 'Steinfurt III'),
       (905, 'Münster'),
       (905, 'Warendorf'),
       (905, 'Gütersloh I'),
       (905, 'Bielefeld – Gütersloh II'),
       (905, 'Herford – Minden-Lübbecke II'),
       (905, 'Minden-Lübbecke I'),
       (905, 'Lippe I'),
       (905, 'Höxter – Gütersloh III – Lippe II'),
       (905, 'Paderborn'),
       (905, 'Hagen – Ennepe-Ruhr-Kreis I'),
       (905, 'Ennepe-Ruhr-Kreis II'),
       (905, 'Bochum I'),
       (905, 'Herne – Bochum II'),
       (905, 'Dortmund I'),
       (905, 'Dortmund II'),
       (905, 'Unna I'),
       (905, 'Hamm – Unna II'),
       (905, 'Soest'),
       (905, 'Hochsauerlandkreis'),
       (905, 'Siegen-Wittgenstein'),
       (905, 'Olpe – Märkischer Kreis I'),
       (905, 'Märkischer Kreis II'),
       (906, 'Waldeck'),
       (906, 'Kassel'),
       (906, 'Werra-Meißner – Hersfeld-Rotenburg'),
       (906, 'Schwalm-Eder'),
       (906, 'Marburg'),
       (906, 'Lahn-Dill'),
       (906, 'Gießen'),
       (906, 'Fulda'),
       (906, 'Main-Kinzig – Wetterau II – Schotten'),
       (906, 'Hochtaunus'),
       (906, 'Wetterau I'),
       (906, 'Rheingau-Taunus – Limburg'),
       (906, 'Wiesbaden'),
       (906, 'Hanau'),
       (906, 'Main-Taunus'),
       (906, 'Frankfurt am Main I'),
       (906, 'Frankfurt am Main II'),
       (906, 'Groß-Gerau'),
       (906, 'Offenbach'),
       (906, 'Darmstadt'),
       (906, 'Odenwald'),
       (906, 'Bergstraße'),
       (907, 'Neuwied'),
       (907, 'Ahrweiler'),
       (907, 'Koblenz'),
       (907, 'Mosel/Rhein-Hunsrück'),
       (907, 'Kreuznach'),
       (907, 'Bitburg'),
       (907, 'Trier'),
       (907, 'Montabaur'),
       (907, 'Mainz'),
       (907, 'Worms'),
       (907, 'Ludwigshafen/Frankenthal'),
       (907, 'Neustadt – Speyer'),
       (907, 'Kaiserslautern'),
       (907, 'Pirmasens'),
       (907, 'Südpfalz'),
       (908, 'Stuttgart I'),
       (908, 'Stuttgart II'),
       (908, 'Böblingen'),
       (908, 'Esslingen'),
       (908, 'Nürtingen'),
       (908, 'Göppingen'),
       (908, 'Waiblingen'),
       (908, 'Ludwigsburg'),
       (908, 'Neckar-Zaber'),
       (908, 'Heilbronn'),
       (908, 'Schwäbisch Hall – Hohenlohe'),
       (908, 'Backnang – Schwäbisch Gmünd'),
       (908, 'Aalen – Heidenheim'),
       (908, 'Karlsruhe-Stadt'),
       (908, 'Karlsruhe-Land'),
       (908, 'Rastatt'),
       (908, 'Heidelberg'),
       (908, 'Mannheim'),
       (908, 'Odenwald – Tauber'),
       (908, 'Rhein-Neckar'),
       (908, 'Bruchsal – Schwetzingen'),
       (908, 'Pforzheim'),
       (908, 'Calw'),
       (908, 'Freiburg'),
       (908, 'Lörrach – Müllheim'),
       (908, 'Emmendingen – Lahr'),
       (908, 'Offenburg'),
       (908, 'Rottweil – Tuttlingen'),
       (908, 'Schwarzwald-Baar'),
       (908, 'Konstanz'),
       (908, 'Waldshut'),
       (908, 'Reutlingen'),
       (908, 'Tübingen'),
       (908, 'Ulm'),
       (908, 'Biberach'),
       (908, 'Bodensee'),
       (908, 'Ravensburg'),
       (908, 'Zollernalb – Sigmaringen'),
       (909, 'Altötting'),
       (909, 'Erding – Ebersberg'),
       (909, 'Freising'),
       (909, 'Fürstenfeldbruck'),
       (909, 'Ingolstadt'),
       (909, 'München-Nord'),
       (909, 'München-Ost'),
       (909, 'München-Süd'),
       (909, 'München-West/Mitte'),
       (909, 'München-Land'),
       (909, 'Rosenheim'),
       (909, 'Bad Tölz-Wolfratshausen – Miesbach'),
       (909, 'Starnberg – Landsberg am Lech'),
       (909, 'Traunstein'),
       (909, 'Weilheim'),
       (909, 'Deggendorf'),
       (909, 'Landshut'),
       (909, 'Passau'),
       (909, 'Rottal-Inn'),
       (909, 'Straubing'),
       (909, 'Amberg'),
       (909, 'Regensburg'),
       (909, 'Schwandorf'),
       (909, 'Weiden'),
       (909, 'Bamberg'),
       (909, 'Bayreuth'),
       (909, 'Coburg'),
       (909, 'Hof'),
       (909, 'Kulmbach'),
       (909, 'Ansbach'),
       (909, 'Erlangen'),
       (909, 'Fürth'),
       (909, 'Nürnberg-Nord'),
       (909, 'Nürnberg-Süd'),
       (909, 'Roth'),
       (909, 'Aschaffenburg'),
       (909, 'Bad Kissingen'),
       (909, 'Main-Spessart'),
       (909, 'Schweinfurt'),
       (909, 'Würzburg'),
       (909, 'Augsburg-Stadt'),
       (909, 'Augsburg-Land'),
       (909, 'Donau-Ries'),
       (909, 'Neu-Ulm'),
       (909, 'Oberallgäu'),
       (909, 'Ostallgäu'),
       (910, 'Saarbrücken'),
       (910, 'Saarlouis'),
       (910, 'St. Wendel'),
       (910, 'Homburg'),
       (911, 'Berlin-Mitte'),
       (911, 'Berlin-Pankow'),
       (911, 'Berlin-Reinickendorf'),
       (911, 'Berlin-Spandau – Charlottenburg Nord'),
       (911, 'Berlin-Steglitz-Zehlendorf'),
       (911, 'Berlin-Charlottenburg-Wilmersdorf'),
       (911, 'Berlin-Tempelhof-Schöneberg'),
       (911, 'Berlin-Neukölln'),
       (911, 'Berlin-Friedrichshain-Kreuzberg – Prenzlauer Berg Ost'),
       (911, 'Berlin-Treptow-Köpenick'),
       (911, 'Berlin-Marzahn-Hellersdorf'),
       (911, 'Berlin-Lichtenberg'),
       (912, 'Prignitz – Ostprignitz-Ruppin – Havelland I'),
       (912, 'Uckermark – Barnim I'),
       (912, 'Oberhavel – Havelland II'),
       (912, 'Märkisch-Oderland – Barnim II'),
       (912, 'Brandenburg an der Havel – Potsdam-Mittelmark I – Havelland III – Teltow-Fläming I'),
       (912, 'Potsdam – Potsdam-Mittelmark II – Teltow-Fläming II'),
       (912, 'Dahme-Spreewald – Teltow-Fläming III – Oberspreewald-Lausitz I'),
       (912, 'Frankfurt (Oder) – Oder-Spree'),
       (912, 'Cottbus – Spree-Neiße'),
       (912, 'Elbe-Elster – Oberspreewald-Lausitz II'),
       (913, 'Schwerin – Ludwigslust-Parchim I – Nordwestmecklenburg I'),
       (913, 'Ludwigslust-Parchim II – Nordwestmecklenburg II – Landkreis Rostock I'),
       (913, 'Rostock – Landkreis Rostock II'),
       (913, 'Vorpommern-Rügen – Vorpommern-Greifswald I'),
       (913, 'Mecklenburgische Seenplatte I – Vorpommern-Greifswald II'),
       (913, 'Mecklenburgische Seenplatte II – Landkreis Rostock III'),
       (914, 'Nordsachsen'),
       (914, 'Leipzig I'),
       (914, 'Leipzig II'),
       (914, 'Leipzig-Land'),
       (914, 'Meißen'),
       (914, 'Bautzen I'),
       (914, 'Görlitz'),
       (914, 'Sächsische Schweiz-Osterzgebirge'),
       (914, 'Dresden I'),
       (914, 'Dresden II – Bautzen II'),
       (914, 'Mittelsachsen'),
       (914, 'Chemnitz'),
       (914, 'Chemnitzer Umland – Erzgebirgskreis II'),
       (914, 'Erzgebirgskreis I'),
       (914, 'Zwickau'),
       (914, 'Vogtlandkreis'),
       (915, 'Altmark'),
       (915, 'Börde – Jerichower Land'),
       (915, 'Harz'),
       (915, 'Magdeburg'),
       (915, 'Dessau – Wittenberg'),
       (915, 'Anhalt'),
       (915, 'Halle'),
       (915, 'Burgenland – Saalekreis'),
       (915, 'Mansfeld'),
       (916, 'Eichsfeld – Nordhausen – Kyffhäuserkreis'),
       (916, 'Eisenach – Wartburgkreis – Unstrut-Hainich-Kreis'),
       (916, 'Jena – Sömmerda – Weimarer Land I'),
       (916, 'Gotha – Ilm-Kreis'),
       (916, 'Erfurt – Weimar – Weimarer Land II'),
       (916, 'Gera – Greiz – Altenburger Land'),
       (916, 'Saalfeld-Rudolstadt – Saale-Holzland-Kreis – Saale-Orla-Kreis'),
       (916, 'Suhl – Schmalkalden-Meiningen – Hildburghausen – Sonneberg');