create table
    public.election
(
    election_id serial,
    year        integer null,
    active      boolean not null default false,
    constraint election_pkey primary key (election_id)
) tablespace pg_default;

create table
    public.district
(
    district_id     serial,
    name            character varying(255) null,
    eligible_voters jsonb                  null,
    voters          jsonb                  null,
    invalid_votes   jsonb                  null,
    valid_votes     jsonb                  null,
    election_id     integer                null,
    state_id        integer                null,
    identifier      integer                null,
    constraint district_pkey primary key (district_id),
    constraint district_state_id_fkey foreign key (state_id) references state (state_id),
    constraint district_election_id_fkey foreign key (election_id) references election (election_id)
) tablespace pg_default;

create table
    public.party_votes
(
    vote_id     serial,
    votes       jsonb   null,
    party_id    integer null,
    district_id integer null,
    constraint party_votes_pkey primary key (vote_id),
    constraint party_votes_party_id_fkey foreign key (party_id) references party (party_id),
    constraint party_votes_district_id_fkey foreign key (district_id) references district (district_id)
) tablespace pg_default;

create table
    public.party
(
    party_id    serial,
    name        character varying(255) null,
    election_id integer                null,
    color_hex   text                   null,
    constraint party_pkey primary key (party_id),
    constraint party_election_id_fkey foreign key (election_id) references election (election_id)
) tablespace pg_default;

create table
    public.state_votes
(
    state_votes_id  bigint generated by default as identity,
    election_id     integer null,
    eligible_voters jsonb   null,
    voters          jsonb   null,
    invalid_votes   jsonb   null,
    valid_votes     jsonb   null,
    state_id        integer null,
    constraint state_votes_pkey primary key (state_votes_id),
    constraint state_votes_state_id_fkey foreign key (state_id) references state (state_id),
    constraint state_votes_election_id_fkey foreign key (election_id) references election (election_id)
) tablespace pg_default;

create table
    public.state
(
    state_id     serial,
    name         character varying(255) null,
    identifier   integer                null,
    abbreviation text                   null,
    constraint state_pkey primary key (state_id)
) tablespace pg_default;